image:https://github.com/rwinch/antora-gradle-plugin/workflows/check/badge.svg?branch=main["build Status", link="https://github.com/rwinch/antora-gradle-plugin/actions?query=workflow%3Acheck"]


A very simple Gradle plugin to automatically download and install https://antora.org[Antora], a documentation site generator capable of aggregating content from multiple repositories.

= Usage

The first step is to apply the Gradle plugin.

.build.gradle
[source,groovy]
----
plugins {
  id "io.github.rwinch.antora" version "0.0.2"
}
----

The next step is to run the antora task:

[source,bash]
----
./gradlew antora
----

The plugin provides an extension that allows customizations:

.build.gradle
[source,groovy]
----
antora {
    // default: "antora-playbook.yml"
    playbookFile = file("local-playbook.yml")
    // default no version (current version)
    antoraVersion = "2.3.4"
    // additional arguments (other than playbookFile) to pass to Antora. Default is emptyList
    arguments = ["--fetch"]
}
----


= Snapshots

The plugin does not currently deploy SNAPSHOTs.
To use the latest snapshot:

* Clone the repository and remember the location.
  We will refer to that location as `$AGP_HOME`.
* In the project that uses `antora-gradle-plugin`
** Update to use the latest Gradle version
** Update the version to match the `version` in `gradle.properties`.
  For example, to run `0.0.2-SNAPSHOT` use the following.
+
.build.gradle
[source,groovy]
----
plugins {
  id "io.github.rwinch.antora" version "0.0.3-SNAPSHOT"
}
----
** Execute the build as a https://docs.gradle.org/current/userguide/composite_builds.html[composite build].
  For example:
+
[source,bash]
----
./gradlew antora --include-build $AGP_HOME
----

= Sample

For a complete sample refer to https://github.com/rwinch/antora-gradle


= License

This project is Open Source software released under the http://www.apache.org/licenses/LICENSE-2.0.html[Apache 2.0 license].
